In [1]:
import pandas as pd
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
match=pd.read_csv('matches.csv')
delivery=pd.read_csv('deliveries.csv')
ipl=delivery.merge(match,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [3]:
# ipl=pd.read_csv('ipl_full_data.csv')
# ipl.head()

# Created ipl data set in csv file

In [67]:
# ipl.to_csv('ipl_full_data.csv', index=False)

In [4]:
top100=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(100).index.tolist()
new_ipl=ipl[ipl['batter'].isin(top100)]

In [5]:
runs=new_ipl.groupby('batter')['batsman_runs'].sum()
balls=new_ipl.groupby('batter')['batsman_runs'].count()
strike_rate=(runs/balls)*100
strike_rate=strike_rate.reset_index()
strike_rate.head(50)

              batter  batsman_runs
0     AB de Villiers    148.580442
1       AC Gilchrist    133.054662
2         AD Russell    164.224422
3           AJ Finch    123.349057
4         AK Markram    126.429479
5          AM Rahane    120.321410
6           AR Patel    125.417299
7          AT Rayudu    124.584527
8    Abhishek Sharma    148.864865
9    B Sai Sudharsan    134.285714
10       BB McCullum    126.848592
11          BJ Hodge    121.422376
12           CA Lynn    136.447639
13          CH Gayle    142.121729
14        D Padikkal    117.838246
15         DA Miller    134.684477
16         DA Warner    135.429986
17          DJ Bravo    125.100241
18          DJ Hooda    125.299145
19         DJ Hussey    120.072661
20  DPMD Jayawardene    118.791064
21          DR Smith    132.279534
22        EJG Morgan    119.051651
23      F du Plessis    133.071325
24         G Gambhir    119.665153
25        GJ Maxwell    150.488599
26         H Klaasen    161.990212
27         HH Pandya    139.691290
28         IK Pathan    116.751269
29      Ishan Kishan    132.797589
30         JA Morkel    136.938202
31        JC Buttler    142.238984
32         JH Kallis    105.936272
33       JM Bairstow    140.371025
34         JP Duminy    120.773810
35        KA Pollard    140.457703
36     KC Sangakkara    118.469101
37        KD Karthik    131.353404
38         KH Pandya    127.972028
39           KK Nair    125.503356
40          KL Rahul    131.050866
41         KM Jadhav    119.367589
42      KP Pietersen    132.058047
43     KS Williamson    122.952710
44       LMP Simmons    122.892938
45       LRPL Taylor    120.070838
46           M Vijay    118.614130
47           M Vohra    125.492468
48        MA Agarwal    128.255646
49      MC Henriques    124.843945

In [ ]:
out = ipl[ipl['player_dismissed'].isin(top100)]
number_of_out = out['player_dismissed'].value_counts()
avg = runs / number_of_out
avg = avg.reset_index()
avg.rename(columns={'index': 'batter', 0: 'avg'}, inplace=True)
avg = avg.merge(strike_rate, on='batter')     
number_of_out.head(20)'

player_dismissed
RG Sharma         223
V Kohli           207
S Dhawan          193
KD Karthik        184
RV Uthappa        180
SK Raina          171
DA Warner         164
AT Rayudu         155
AM Rahane         154
SV Samson         144
G Gambhir         136
MS Dhoni          134
MK Pandey         133
AB de Villiers    130
F du Plessis      127
CH Gayle          126
SR Watson         126
PA Patel          126
WP Saha           121
KA Pollard        121
Name: count, dtype: int64

In [50]:
out = ipl[ipl['player_dismissed'].isin(top100)]
number_of_out = out['player_dismissed'].value_counts()
avg = runs / number_of_out
avg = avg.reset_index()
avg.rename(columns={'index': 'batter', 0: 'avg'}, inplace=True)
avg = avg.merge(strike_rate, on='batter')
number_of_out.head(20)
avg.head(30)

              batter        avg  Strike_rate
0     AB de Villiers  39.853846   148.580442
1       AC Gilchrist  27.223684   133.054662
2         AD Russell  28.930233   164.224422
3           AJ Finch  24.904762   123.349057
4         AK Markram  30.151515   126.429479
5          AM Rahane  30.142857   120.321410
6           AR Patel  21.467532   125.417299
7          AT Rayudu  28.051613   124.584527
8    Abhishek Sharma  25.500000   148.864865
9    B Sai Sudharsan  47.000000   134.285714
10       BB McCullum  27.711538   126.848592
11          BJ Hodge  33.333333   121.422376
12           CA Lynn  34.076923   136.447639
13          CH Gayle  39.658730   142.121729
14        D Padikkal  25.145161   117.838246
15         DA Miller  35.658537   134.684477
16         DA Warner  40.042683   135.429986
17          DJ Bravo  22.608696   125.100241
18          DJ Hooda  18.325000   125.299145
19         DJ Hussey  26.979592   120.072661
20  DPMD Jayawardene  28.250000   118.791064
21          DR Smith  28.392857   132.279534
22        EJG Morgan  22.677419   119.051651
23      F du Plessis  35.992126   133.071325
24         G Gambhir  31.007353   119.665153
25        GJ Maxwell  24.750000   150.488599
26         H Klaasen  38.192308   161.990212
27         HH Pandya  28.471910   139.691290
28         IK Pathan  21.698113   116.751269
29      Ishan Kishan  28.430108   132.797589

# 1.Scatter plot

In [7]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers')
data=[trace]
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Add batsman name in this plot

In [77]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batter'])  #Add this(text=avg['batter'])
data=[trace]
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)
data=[trace]
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Add color

In [79]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batter'],marker={'color':'#00a65a'}) # Add color(marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Increasing size

In [82]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batter'],marker={'color':'#00a65a','size':16}) #marker={'color':'#00a65a','size':16}
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Change the file name

In [83]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batter'],marker={'color':'#00a65a','size':16}) 
layout=go.Layout(title="Batsman Average vs Srtick_Rate",
xaxis={'title':'Batsman Average'},yaxis={'title':'Batsman Strike Rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='myfile.html') #add(filename='myfile.html')

'myfile.html'

# 2.Line Chart

In [84]:
#Year By Year Batsman Performance
single=ipl[ipl['batter']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance

     season  batsman_runs
0   2007/08           165
1      2009           246
2   2009/10           307
3      2011           557
4      2012           364
5      2013           639
6      2014           359
7      2015           505
8      2016           973
9      2017           308
10     2018           530
11     2019           464
12  2020/21           471
13     2021           405
14     2022           341
15     2023           639
16     2024           741

In [85]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines',marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title='Year by year performance',xaxis={'title':'Season'},yaxis={'title':'Total Runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Add marker

In [97]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines+markers',marker={'color':'#00a65a','size':20})
data=[trace]
layout=go.Layout(title='Year by year performance',xaxis={'title':'Season'},yaxis={'title':'Total Runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Multiple Line plot

In [15]:
single=ipl[ipl['batter']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()
performance
single1=ipl[ipl['batter']=='MS Dhoni']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

     season  batsman_runs
0   2007/08           414
1      2009           332
2   2009/10           287
3      2011           392
4      2012           358
5      2013           461
6      2014           371
7      2015           372
8      2016           284
9      2017           290
10     2018           455
11     2019           416
12  2020/21           200
13     2021           114
14     2022           232
15     2023           104
16     2024           161

In [16]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines+markers',marker={'color':'#00a65a'},name='V Kohli')
trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],mode='lines+markers',name='MS Dhoni')
data=[trace,trace1]
layout=go.Layout(title='Year by year performance',xaxis={'title':'Season'},yaxis={'title':'Total Runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [20]:
def batsman_comp(*name):
    data = []
    for i in name:
        single = ipl[ipl['batter'] == i]
        performance = single.groupby('season')['batsman_runs'].sum().reset_index()
        trace = go.Scatter(x=performance['season'], y=performance['batsman_runs'],
                           mode='lines+markers', name=i)
        data.append(trace)

    layout = go.Layout(title='Batsman Record Comparator',
                       xaxis={'title': 'Season'},
                       yaxis={'title': 'Runs'})

    fig = go.Figure(data=data, layout=layout)
    pyo.plot(fig, filename='year_by_year')

In [23]:
batsman_comp('AB de Villiers','V Kohli','MS Dhoni','SK Raina')

c:\Users\tanma\Lib\site-packages\plotly\offline\offline.py:556: UserWarning:

Your filename `year_by_year` didn't end with .html. Adding .html to the end of your file.

In [18]:
batsman_comp('AB de Villiers','V Kohli','MS Dhoni','MK Pandey' ,'S Dhawan','RG Sharma','SK Raina ')

c:\Users\tanma\Lib\site-packages\plotly\offline\offline.py:556: UserWarning:

Your filename `year_by_year` didn't end with .html. Adding .html to the end of your file.

# Bar Plot

In [31]:
top10=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.tolist()
top10_df=ipl[ipl['batter'].isin(top10)]

In [32]:
top10_score=top10_df.groupby('batter')['batsman_runs'].sum().reset_index()
top10_score

           batter  batsman_runs
0  AB de Villiers          5181
1        CH Gayle          4997
2       DA Warner          6567
3      KD Karthik          4843
4        MS Dhoni          5243
5       RG Sharma          6630
6      RV Uthappa          4954
7        S Dhawan          6769
8        SK Raina          5536
9         V Kohli          8014

In [39]:
# Plot Bar Graph
trace=go.Bar(x=top10_score['batter'],y=top10_score['batsman_runs'],marker={'color':'#00a65a'})
data=[trace]
layout=go.Layout(title='Top 10 IPL batsman',xaxis={'title':'batter'},yaxis={'title':'Total_Runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

# There are 3 types of Bar Graphs
#1.Nested Bar Graph
#2.Stacked Bar Garph
#3.Overlayed Bar Graph

In [44]:
iw=top10_df.groupby(['batter','inning'])['batsman_runs'].sum().reset_index()
mask1=iw['inning']==1
mask2=iw['inning']==2
one=iw[mask1]
two=iw[mask2]
mask1=iw['inning']==1
one.rename(columns={'batsman_runs':'1st Innings'},inplace=True)
two.rename(columns={'batsman_runs':'2nd Innings'},inplace=True)
final=one.merge(two,on='batter')[['batter','1st Innings','2nd Innings']]
final.head(15)

C:\Users\tanma\AppData\Local\Temp\ipykernel_31688\3383124442.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\tanma\AppData\Local\Temp\ipykernel_31688\3383124442.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           batter  1st Innings  2nd Innings
0  AB de Villiers         3163         1999
1        CH Gayle         2873         2092
2       DA Warner         3280         3285
3      KD Karthik         2743         2099
4        MS Dhoni         3065         2178
5       RG Sharma         3600         3028
6      RV Uthappa         2120         2832
7        S Dhawan         3926         2843
8        SK Raina         3194         2334
9         V Kohli         4400         3604

Overlayed Bar Graph

In [49]:
trace1=go.Bar(x=final['batter'],y=final['1st Innings'],name='1st innings',marker={'color':'#00a65a'})
trace2=go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd innings')
data=[trace1,trace2]
layout=go.Layout(title='Inning wise Scores',xaxis={'title':'Batsman'},yaxis={'title':'Runs'},barmode='overlay')
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Stacked Bar Garph

In [50]:
trace1=go.Bar(x=final['batter'],y=final['1st Innings'],name='1st innings',marker={'color':'#00a65a'})
trace2=go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd innings')
data=[trace1,trace2]
layout=go.Layout(title='Inning wise Scores',xaxis={'title':'Batsman'},yaxis={'title':'Runs'},barmode='stack')
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

Nested Bar Graph

In [51]:
trace1=go.Bar(x=final['batter'],y=final['1st Innings'],name='1st innings',marker={'color':'#00a65a'})
trace2=go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd innings')
data=[trace1,trace2]
layout=go.Layout(title='Inning wise Scores',xaxis={'title':'Batsman'},yaxis={'title':'Runs'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

# 4.Bubble plot

In [53]:
avg

             batter        avg  batsman_runs
0    AB de Villiers  39.853846    148.580442
1      AC Gilchrist  27.223684    133.054662
2        AD Russell  28.930233    164.224422
3          AJ Finch  24.904762    123.349057
4        AK Markram  30.151515    126.429479
..              ...        ...           ...
95          WP Saha  24.247934    123.902027
96  Y Venugopal Rao  22.386364    113.872832
97      YBK Jaiswal  32.140000    146.757991
98        YK Pathan  29.290909    138.046272
99     Yuvraj Singh  24.810811    124.784776

[100 rows x 3 columns]

In [60]:
six_1=new_ipl=new_ipl[new_ipl['batsman_runs']==6]                          #(batsman_runs_y )means six number
six=new_ipl.groupby('batter')['batsman_runs'].count().reset_index()
x=avg.merge(six,on='batter')
x

             batter        avg  batsman_runs_x  batsman_runs_y
0    AB de Villiers  39.853846      148.580442             253
1      AC Gilchrist  27.223684      133.054662              92
2        AD Russell  28.930233      164.224422             209
3          AJ Finch  24.904762      123.349057              78
4        AK Markram  30.151515      126.429479              35
..              ...        ...             ...             ...
95          WP Saha  24.247934      123.902027              87
96  Y Venugopal Rao  22.386364      113.872832              37
97      YBK Jaiswal  32.140000      146.757991              64
98        YK Pathan  29.290909      138.046272             161
99     Yuvraj Singh  24.810811      124.784776             149

[100 rows x 4 columns]

In [69]:
trace=go.Scatter(x=x['avg'],y=x['batsman_runs_x'],mode='markers',marker={'size':x['batsman_runs_y']})
data=[trace]
layout=go.Layout(title="Bubble chart",xaxis={'title':'Avarage'},yaxis={'title':'Strick_rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [70]:
trace=go.Scatter(x=x['avg'],y=x['batsman_runs_x'],mode='markers',marker={'size':x['batsman_runs_y']},text=x['batter'])   #Add batsman name(text=x['batter']
data=[trace]
layout=go.Layout(title="Bubble chart",xaxis={'title':'Avarage'},yaxis={'title':'Strick_rate'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

# 5.Box plot

In [83]:
match_agg=delivery.groupby(['match_id'])['total_runs'].sum().reset_index()
season_wise=match_agg.merge(match,left_on='match_id',right_on='id')[['match_id','total_runs','season']]
season_wise

      match_id  total_runs   season
0       335982         304  2007/08
1       335983         447  2007/08
2       335984         261  2007/08
3       335985         331  2007/08
4       335986         222  2007/08
...        ...         ...      ...
1090   1426307         429     2024
1091   1426309         323     2024
1092   1426310         346     2024
1093   1426311         314     2024
1094   1426312         227     2024

[1095 rows x 3 columns]

In [84]:
trace=go.Box(x=season_wise['total_runs'],name="All seasons")
data=[trace]
layout=go.Layout(title='Total Score Analysis',xaxis={'title':'Total Score'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [82]:
trace1 = go.Box(x=season_wise[season_wise['season'] == 2017]['total_runs'], name='2017', marker={'color': 'blue'})
trace2 = go.Box(x=season_wise[season_wise['season'] == 2008]['total_runs'], name='2008')  # or '2016'
data = [trace1, trace2]
layout = go.Layout(title='Total Score Analysis', xaxis={'title': 'Total Score'})
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

# 7.Displots

In [88]:
import plotly.figure_factory as ff
hist_data=[avg['avg']]
group_labels=['Average']
fig=ff.create_distplot(hist_data,group_labels)
pyo.plot(fig)

'temp-plot.html'

imports Plotly's Figure Factory module under the alias ff. This module provides high‑level helper functions for creating specialized chart types that are otherwise complex to set up manually. These include plots like:

Dendrograms (hierarchical clustering trees)

Quiver (vector arrow) plots

Streamline flow visualizations

Tables, ternary or triangulated surface plots, and hexagon‑bin maps

In [92]:
import plotly.figure_factory as ff
hist_data=[avg['avg'],avg['batsman_runs']]
group_labels=['Average','Strick_rate']
fig=ff.create_distplot(hist_data,group_labels)
pyo.plot(fig)

'temp-plot.html'

In [91]:
import plotly.figure_factory as ff
hist_data=[avg['avg'],avg['batsman_runs']]
group_labels=['Average','Strick_rate']
fig=ff.create_distplot(hist_data,group_labels,bin_size=[10,12])
pyo.plot(fig)

'temp-plot.html'

# 8.Histogram

In [96]:
# this batter who play atlist 150 ball
x=delivery.groupby('batter')['batsman_runs'].count()>150
x=x[x].index.tolist()
new=delivery[delivery['batter'].isin(x)]
runs=new.groupby('batter')['batsman_runs'].sum()
balls=new.groupby('batter')['batsman_runs'].count()
strick_rate=(runs/balls)*100
strick_rate=strick_rate.reset_index()
strick_rate

              batter  batsman_runs
0     A Ashish Reddy    142.857143
1           A Badoni    125.544554
2          A Manohar    127.624309
3           A Mishra     86.590909
4          A Symonds    124.711908
..               ...           ...
235  Y Venugopal Rao    113.872832
236      YBK Jaiswal    146.757991
237        YK Pathan    138.046272
238      YV Takawale    104.918033
239     Yuvraj Singh    124.784776

[240 rows x 2 columns]

In [100]:
# Plot Histogram
trace=go.Histogram(x=strick_rate['batsman_runs'])
data=[trace]
layout=go.Layout(title='Strick Rate Analysis',xaxis={'title':'Strike Rates'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [101]:
# Plot Histogram
trace=go.Histogram(x=strick_rate['batsman_runs'],xbins={'size':2})
data=[trace]
layout=go.Layout(title='Strick Rate Analysis',xaxis={'title':'Strike Rates'})
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

# 8.Heatmaps

In [106]:
six=delivery[delivery['batsman_runs']==6]
six=six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
six.head(100)

           batting_team  over  batsman_runs
0   Chennai Super Kings     0             9
1   Chennai Super Kings     1            36
2   Chennai Super Kings     2            67
3   Chennai Super Kings     3            71
4   Chennai Super Kings     4            75
..                  ...   ...           ...
95        Gujarat Lions    15             5
96        Gujarat Lions    16             7
97        Gujarat Lions    17             9
98        Gujarat Lions    18             9
99        Gujarat Lions    19             4

[100 rows x 3 columns]

In [108]:
#Plot Heatmap
trace=go.Heatmap(x=six['batting_team'],y=six['over'],z=six['batsman_runs'])
data=[trace]
layout=go.Layout(title='Six Heatmap')
fig=go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [112]:
dots=delivery[delivery['batsman_runs']==0]
dots=dots.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
from plotly import tools
trace1=go.Heatmap(x=six['batting_team'],y=six['over'],z=six['batsman_runs'].values.tolist())
trace2=go.Heatmap(x=dots['batting_team'],y=dots['over'],z=dots['batsman_runs'].values.tolist())
fig=tools.make_subplots(rows=1,cols=2,subplot_titles=["6's","0's"],shared_yaxes=True)
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
pyo.plot(fig)

c:\Users\tanma\Lib\site-packages\plotly\tools.py:453: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead

'temp-plot.html'